CREATE DATABASE IF NOT EXISTS `db01`;
CREATE DATABASE IF NOT EXISTS `db02`;
CREATE DATABASE IF NOT EXISTS `db03`;
CREATE DATABASE IF NOT EXISTS `db04`;
CREATE DATABASE IF NOT EXISTS `db05`;

ALTER DATABASE db01 CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER DATABASE db02 CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER DATABASE db03 CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER DATABASE db04 CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER DATABASE db05 CHARACTER SET utf8 COLLATE utf8_general_ci;