server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
#      globalcors:
#        corsConfigurations:
#          '[/**]':
#            allowedOrigins: "http://localhost:3000"
#            allowedHeaders: "*"
#            allowedMethods:
#            - GET
#            - POST
#      routes:
#        - id: auth-service
#          uri: lb://auth-service
#          predicates:
#            - Path=/auth/**
#          filters:
#            - RewritePath=/auth/(?<path>.*), /$\{path}
#        - id: forum-service
#          uri: lb://forum-service
#          predicates:
#            - Path=/forum/**
#          filters:
#            - AuthFilters
          
management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

jwt.secret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1

eureka:
  instance:
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
micro-service:
  system-service: http://localhost:8081
  post-service: http://localhost:8082
  notify-service: http://localhost:8083
  chat-service: http://localhost:8084
  user-service: http://localhost:8088
  auth-service: http://localhost:8089
  api-gateway: http://localhost:8080
  eureka-service: http://localhost:8761
  config-service: http://localhost:8071