eureka:
  instance:
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8084
  
spring:
  application:
    name: chat-service
  datasource:
    url: jdbc:mysql://localhost:3306/db05
    username: root
    password: Zaq12wsx1234
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
    host: localhost
    port: 5672
    username: admin
    password: Zaq12wsx1234

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

micro-service:
  system-service: http://localhost:8081
  post-service: http://localhost:8082
  notify-service: http://localhost:8083
  chat-service: http://localhost:8084
  user-service: http://localhost:8088
  auth-service: http://localhost:8089
  api-gateway: http://localhost:8080
  eureka-service: http://localhost:8761
  config-service: http://localhost:8071

