spring:
  application:
    name: eureka-server
  boot:
    admin:
      context-path: /admin
  cloud:
    config:
      enabled: false
server:
  port: 8761
eureka:
  instance:
    hostname: eurekaserver
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 5
    enableSelfPreservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

micro-service:
  system-service: http://localhost:8081
  post-service: http://localhost:8082
  notify-service: http://localhost:8083
  chat-service: http://localhost:8084
  user-service: http://localhost:8088
  auth-service: http://localhost:8089
  api-gateway: http://localhost:8080
  eureka-service: http://localhost:8761
  config-service: http://localhost:8071

