spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db03
    username: root
    password: Zaq12wsx1234
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
