eureka:
  instance:
    preferIpAddress: true 
  client:
    registerWithEureka: true
    fetchRegistry : true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081
  
spring:
  application:
    name: system-service
  datasource:
    url: jdbc:mysql://localhost:3306/db01
    username: root
    password: Zaq12wsx1234
    hikari:
      data-source-properties:
        useUnicode: true
        characterEncoding: UTF-8
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 3s
          max-attempts: 6
          max-interval: 10s
          multiplier: 2
    host: localhost
    port: 5672
    username: admin
    password: Zaq12wsx1234
  mail:
    host: smtp.gmail.com
    port: 578
    username: thanhvinhse94@gmail.com
    password: ufvyhnljytcdwaxu
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true


