version: "3"
services:
  mysql:
    image: mysql:5.7.37
    container_name: mysql-forum
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Zaq12wsx1234
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - parent-share-forum

networks:
  parent-share-forum:
